'use strict';

angular.module('jacobharasimoApp')
    .controller('AboutCtrl', function ($scope,Page) {
        Page.setTitle("About");

        $scope.Technologies=[
            {
                Title:'HTMl5',
                URL:'../images/HTML5.png',
                Link:'http://en.wikipedia.org/wiki/HTML5'
            },
            {
                Title:'AngularJS',
                URL:'../images/angularJS.png',
                Link:'http://angularjs.org/'
            },
            {
                Title:'MVC4',
                URL:'../images/MVC4.png',
                Link:'http://www.asp.net/mvc/mvc4'
            },
            {
                Title:'CSS3',
                URL:'../images/css3.png',
                Link:'http://www.w3schools.com/css3/'
            },
            {
                Title:'AJAX',
                URL:'../images/ajax.png',
                Link:''
            },
            {
                Title:'Javascript',
                URL:'../images/javascript.png',
                Link:''
            },
            {
                Title:'C#',
                URL:'../images/csharp.png',
                Link:''
            },
            {
                Title:'Silverlight',
                URL:'../images/silverlight.png',
                Link:''
            },
            {
                Title:'PHP',
                URL:'../images/php.png',
                Link:''
            },
            {
                Title:'jQuery',
                URL:'../images/jquery.png',
                Link:'http://jquery.com/'
            },
            {
                Title:'JqueryMobile',
                URL:'../images/jquery_mobile.png',
                Link:'http://jquerymobile.com/'
            },
            {
                Title:'nodeJS',
                URL:'../images/nodejs.png',
                Link:'http://nodejs.org/'
            },
            {
                Title:'Grunt',
                URL:'../images/grunt.png',
                Link:'http://gruntjs.com/'
            },
            {
                Title:'Wordpress',
                URL:'../images/wordpress.png',
                Link:'http://en-ca.wordpress.org/'
            },
            {
                Title:'Bootstrap',
                URL:'../images/twitter_bootstrap.png',
                Link:'http://getbootstrap.com/'
            },
            {
                Title:'Foundation',
                URL:'../images/foundationjs.jpg',
                Link:'http://foundation.zurb.com/'
            },
            {
                Title:'ASP.net',
                URL:'../images/aspnet.png',
                Link:'http://www.asp.net/'
            },
            {
                Title:'Drupal',
                URL:'../images/drupal.png',
                Link:'https://drupal.org/'
            }

        ];
    });
